OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer0
        SANS:
          - {IP-HOST-1}
      - Hostname: orderer1
        SANS:
          - {IP-HOST-2}

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer
        SANS:
          - {IP-HOST-1}
          - {IP-HOST-2}
    Template:
      Count: 4
    Users:
      Count: 0
