OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer0
        SANS:
          - {IP-HOST-1}
          {Orderer Hostname SANS}
      #- Hostname: orderer1
      #  SANS:
      #    - {IP-HOST-2}

PeerOrgs:
  - Name: Org1
    Domain: org1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer
        SANS:
          - {IP-HOST-1}
          {Peer SANS}
          #- {IP-HOST-2}
    Template:
      Count: {Num of Peers} #4
    Users:
      Count: 0
